var ioc={
	dataSource:{
		type:"com.alibaba.druid.pool.DruidDataSource",
		events:{depose:"close"},
		fields:{
			driverClassName:"org.h2.Driver",
			url:"jdbc:h2:/home/tt/java/ttcms/trunk/ttcms;AUTO_SERVER=TRUE",
			username:"sa",
			password:""
		}
	},
	dao:{
		type:"org.nutz.dao.impl.NutDao",
		args:[{refer:"dataSource"}]
	},
	markdown:{
		type:"com.petebevin.markdown.MarkdownProcessor"
	}
}